apiVersion: v1
kind: Service
metadata:
  name: CI_PROJECT_NAME
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: CI_PROJECT_NAME
  selector:
    app: CI_PROJECT_NAME
  type: NodePort
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: CI_PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CI_PROJECT_NAME
  template:
    metadata:
      labels:
        app: CI_PROJECT_NAME
    spec:
      containers:
      - name: CI_PROJECT_NAME
        image: registry.cn-hongkong.aliyuncs.com/mastertooc/master:CI_PROJECT_NAME-CI_COMMIT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret
