server:
  servlet:
    context-path: /api/windbase
  port: 8080
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: windbase
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      # 支持懒加载
      hibernate.enable_lazy_load_no_trans: true
      # InnoDB 引擎支持事务
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    #    default-property-inclusion: non_null
    time-zone: GMT+8

info:
  name: windbase
  server:
    port: ${server.port}